version: "3.7"

services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    env_file: ".env"
    extra_hosts:
      - proxy-host:host-gateway
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./app", "http"]

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"