// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	dto "github.com/veleton777/test_work_blum/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// CourseStorage is an autogenerated mock type for the CourseStorage type
type CourseStorage struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, codeFrom, codeTo
func (_m *CourseStorage) Get(ctx context.Context, codeFrom string, codeTo string) (decimal.Decimal, bool) {
	ret := _m.Called(ctx, codeFrom, codeTo)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 decimal.Decimal
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (decimal.Decimal, bool)); ok {
		return rf(ctx, codeFrom, codeTo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) decimal.Decimal); ok {
		r0 = rf(ctx, codeFrom, codeTo)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, codeFrom, codeTo)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, codeFrom, codeTo, data
func (_m *CourseStorage) Set(ctx context.Context, codeFrom string, codeTo string, data dto.CurrencyStorageDTO) {
	_m.Called(ctx, codeFrom, codeTo, data)
}

// NewCourseStorage creates a new instance of CourseStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseStorage {
	mock := &CourseStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
