// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CurrenciesAPI is an autogenerated mock type for the CurrenciesAPI type
type CurrenciesAPI struct {
	mock.Mock
}

// Convert provides a mock function with given fields: ctx, from, to, amount
func (_m *CurrenciesAPI) Convert(ctx context.Context, from string, to string, amount float64) (float64, error) {
	ret := _m.Called(ctx, from, to, amount)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) (float64, error)); ok {
		return rf(ctx, from, to, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) float64); ok {
		r0 = rf(ctx, from, to, amount)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, float64) error); ok {
		r1 = rf(ctx, from, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCurrenciesAPI creates a new instance of CurrenciesAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrenciesAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrenciesAPI {
	mock := &CurrenciesAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
